# Generated by Django 5.0.2 on 2025-06-09 19:12

import django.db.models.deletion
import django.utils.timezone
import gestion_facturas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('punto_venta', models.CharField(max_length=5)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('cuit_emisor', models.CharField(blank=True, max_length=13, null=True)),
                ('razon_social_emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=gestion_facturas.models.factura_imagen_path)),
                ('tipo_factura', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], default='B', max_length=1)),
                ('condicion_venta', models.CharField(choices=[('CONTADO', 'Contado'), ('CUENTA_CORRIENTE', 'Cuenta Corriente'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('OTRO', 'Otro')], default='CONTADO', max_length=20)),
                ('condicion_iva', models.CharField(choices=[('RESPONSABLE_INSCRIPTO', 'Responsable Inscripto'), ('RESPONSABLE_NO_INSCRIPTO', 'Responsable No Inscripto'), ('EXENTO', 'Exento'), ('MONOTRIBUTO', 'Monotributo'), ('CONSUMIDOR_FINAL', 'Consumidor Final')], default='CONSUMIDOR_FINAL', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percepcion_iibb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros_tributos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_copia', models.CharField(choices=[('ORIGINAL', 'Original'), ('DUPLICADO', 'Duplicado')], default='ORIGINAL', max_length=10)),
                ('razon_social_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ProductoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('importe_bonificado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='gestion_facturas.factura')),
            ],
            options={
                'verbose_name': 'Producto de Factura',
                'verbose_name_plural': 'Productos de Factura',
            },
        ),
    ]
